[mesh]
ds = 0.01            
len.x = 10.0
len.y = 1.0

[save]
nstep = 100 
npads = 6
directory = '~/work/simdata/pipe_flow'

[fluid]
kvisc   = 2.0e-5     
density = 1.0        

[init]
type = 'constant'
velocity.x = 0.1
velocity.y = 0.0

[bndry.left]
type = 'inflow'
value = 0.1 

[bndry.right]
type = 'outflow'
value = nan 

[bndry.top]
type ='noslip'
value = nan 

[bndry.bottom]
type = 'noslip'
value = nan

[stop]       
type  = "time"       
time  = 500.0         
etol  = nan

